# Generated by Django 5.0.6 on 2024-12-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_productattribute_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='letsPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('cardnum', models.CharField(max_length=200)),
                ('expiry', models.CharField(max_length=200)),
                ('cvc', models.CharField(max_length=200)),
            ],
        ),
    ]
