# Generated by Django 5.0.6 on 2024-12-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_letspay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letspay',
            old_name='name',
            new_name='cardname',
        ),
    ]
